// HEX SPARK MAP
const hex_sparks = new Map([
    ['feature1', ['Buried', 'Colourful', 'Adorned', 'Spiked', 'Split', 'Entombed', 'Reflective', 'Veiled', 'Hot', 'Drowned', 'Desecrated', 'Isolated']]
    , ['feature2', ['Brook', 'Seat', 'Pit', 'Cave', 'Monolith', 'Mound', 'Cairn', 'Pond', 'Waterfall', 'Spring', 'Arch', 'Henge']]
    , ['wonder1', ['Seat', 'Pit', 'Cave', 'Monolith', 'Mound', 'Cairn', 'Pond', 'Waterfall', 'Spring', 'Arch', 'Henge', 'Light']]
    , ['wonder2', ['Light', 'Flames', 'Stones', 'Beasts', 'Sparks', 'Trails', 'Mist', 'Colours', 'Plants', 'Wind', 'Water', 'Shadows']]
    , ['landscape1', ['Barren', 'Dry', 'Grey', 'Sparse', 'Sharp', 'Teeming', 'Still', 'Soft', 'Overgrown', 'Vivid', 'Sodden', 'Lush']]
    , ['landscape2', ['Marsh', 'Heath', 'Crags', 'Peaks', 'Forest', 'Valley', 'Hills', 'Meadow', 'Bog', 'Lakes', 'Glades', 'Plain']]
    , ['otherworld1', ['Acidic', 'Black', 'Smoke', 'Frozen', 'Dead', 'Broken', 'Colossal', 'Living', 'Burning', 'Sludge', 'White', 'Sweet']]
    , ['otherworld2', ['Flats', 'Labyrinth', 'Ruins', 'Stairs', 'Desert', 'Craters', 'Cavern', 'Jungle', 'Dunes', 'Tunnels', 'Island', 'Mountain']]
    , ['weather1', ['Gentle', 'Fleeting', 'Persistent', 'Bright', 'Thin', 'Cool', 'Hot', 'Solid', 'Dull', 'Faint', 'Abundant', 'Harsh']]
    , ['weather2', ['Fleeting', 'Persistent', 'Bright', 'Thin', 'Cool', 'Hot', 'Solid', 'Dull', 'Faint', 'Abundant', 'Harsh', 'Aromatic']]
    , ['sky1', ['Glittering', 'Violet', 'Sapphire', 'Pale', 'Fiery', 'Ivory', 'Slate', 'Pink', 'Golden', 'Bloody', 'Bright', 'Inky']]
    , ['sky2', ['Violet', 'Sapphire', 'Pale', 'Fiery', 'Ivory', 'Slate', 'Pink', 'Golden', 'Bloody', 'Bright', 'Inky', 'Crystal']]
    , ['water1', ['Sapphire', 'Pale', 'Fiery', 'Ivory', 'Slate', 'Pink', 'Golden', 'Bloody', 'Bright', 'Inky', 'Crystal', 'Teal']]
    , ['water2', ['Silk', 'Ripples', 'Abyss', 'Churn', 'Froth', 'Mirror', 'Surge', 'Glass', 'Surf', 'Rapids', 'Spray', 'Bubbles']]
    , ['flora1', ['Aromatic', 'Ashen', 'Blooming', 'Twisted', 'Towering', 'Fruitful', 'Stinging', 'Vibrant', 'Brittle', 'Thorny', 'Sturdy', 'Resinous']]
    , ['flora2', ['Grasses', 'Heather', 'Shrubs', 'Brambles', 'Canopy', 'Ferns', 'Trunks', 'Vines', 'Conifers', 'Saplings', 'Reeds', 'Roots']]
    , ['fauna1', ['Watchful', 'Helpful', 'Graceful', 'Loud', 'Mischievous', 'Deceitful', 'Enlightening', 'Placid', 'Beautiful', 'Mighty', 'Hostile', 'Aloof']]
    , ['fauna2', ['Ungulates', 'Songbirds', 'Canines', 'Rodents', 'Amphibians', 'Insects', 'Felines', 'Reptiles', 'Hawks', 'Mustelids', 'Fowl', 'Bears']]
    , ['location1', ['Ashland ', 'Badland ', 'Bamboo forest ', 'Basalt columns ', 'Bay ', 'Beach ', 'Bluff ', 'Bog ', 'Boulder field ', 'Brook ', 'Butte ', 'Caldera ', 'Canyon ', 'Cave ', 'Cliff ', 'Cloud forest', 'Coniferous forest', 'Copse ', 'Crag ', 'Crater ', 'Creek ', 'Crossing ', 'Crystals ', 'Deciduous forest', 'Delta ', 'Dunes ', 'Dust bowl', 'Element ', 'Fen ', 'Fjord ', 'Floodplain ', 'Gas vent', 'Geyser ', 'Glacier ', 'Gorge ', 'Grotto ', 'Grove ', 'Gulch ', 'Heath ', 'Highland ', 'Hollow ', 'Hoodoo ', 'Hot ', 'Ice ', 'Jungle ', 'Knoll ', 'Lagoon ', 'Lair ', 'Lake ', 'Lakebed ', 'Lava field', 'Lava tube', 'Loch', 'Mangrove', 'Marsh', 'Meadow', 'Mesa', 'Mire', 'Moor', 'Mountain', 'Mud plain', 'Oasis', 'Oil seep', 'Pass', 'Pasture', 'Petrified', 'Pit', 'Plateau', 'Pond', 'Prairie', 'Quicksand', 'Rainforest', 'Rapids', 'Ravine', 'Ridge', 'River', 'Riverland', 'Rockslide', 'flat', 'Salt marsh', 'Savanna', 'Scree slope', 'Scrubland', 'Sinkhole', 'Spring', 'Steppe', 'Stream', 'Sulfur spring', 'Swamp', 'Taiga', 'Tar pit', 'Thicket', 'Tundra', 'Valley', 'Volcanic plain', 'Volcano', 'Wasteland', 'Waterfall', 'Wetlands', 'Whirlpool']]
]);

// HOLDING SPARK MAP
const holding_sparks = new Map([
    ['bailey1', ['Filthy', 'Abandoned', 'Joyous', 'Sophisticated', 'Industrious', 'Humble', 'Majestic', 'Hallowed', 'Rustic', 'Solemn', 'Bustling', 'Immaculate']]
    , ['bailey2', ['Marketplace', 'Forge', 'Library', 'Fountain', 'Temple', 'Forum', 'Tomb', 'Garden', 'Hall', 'Workshops', 'Arena', 'Garrison']]
    , ['drama1', ['Betrayal', 'Jealousy', 'Rivalry', 'Infidelity', 'Coup', 'Ambition', 'Redemption', 'Revelation', 'Wrath', 'Greed', 'Banishment', 'Manipulation']]
    , ['drama2', ['Brawl', 'Poison', 'Oath', 'Feast', 'Letters', 'Disguise', 'Inheritance', 'Assassin', 'Family', 'Alcohol', 'Blackmail', 'Gold']]
    , ['food1', ['Spiced', 'Herbal', 'Crunchy', 'Sour', 'Dry', 'Fermented', 'Salted', 'Wet', 'Fatty', 'Chewy', 'Sweet', 'Mild']]
    , ['food2', ['Fish', 'Fruit', 'Stew', 'Mushrooms', 'Pie', 'Cheese', 'Nuts', 'Cake', 'Porridge', 'Bread', 'Vegetable', 'Meat']]
    , ['goods1', ['Military', 'Abundant', 'Traditional', 'Specialist', 'Industrious', 'Innovative', 'Secretive', 'Simple', 'Strong', 'Decorated', 'Fine', 'Lucky']]
    , ['goods2', ['Textile', 'Livestock', 'Grain', 'Mead', 'Tools', 'Stone', 'Wood', 'Pottery', 'Metal', 'Leather', 'Honey', 'Herb']]
    , ['holding1', ['Dark', 'Ruined', 'Hostile', 'Ancient', 'Ornate', 'Wild', 'Pristine', 'Fortified', 'Unfinished', 'Welcoming', 'Proud', 'Bright']]
    , ['holding2', ['Turrets', 'Tower', 'Wall', 'Battlements', 'Citadel', 'Gate', 'Spire', 'Dome', 'Beacons', 'Bridge', 'Pillars', 'Moat']]
    , ['keep1', ['Hearth', 'Throne', 'Musicians', 'Pool', 'Advisers', 'Servants', 'Shrine', 'Table', 'Reliquary', 'Cauldron', 'Chandelier', 'Guards']]
    , ['keep2', ['Garrison', 'Antlers', 'Silver', 'Heraldry', 'Bones', 'Flowers', 'Scripture', 'Jewels', 'Wreaths', 'Candles', 'Fur', 'Tapestries', 'Shields']]
    , ['luxuries1', ['Antique', 'Intricate', 'Unique', 'Scarce', 'Hazardous', 'Flawless', 'Luminous', 'Lost', 'Esoteric', 'Sacred', 'Mythical', 'Beautiful']]
    , ['luxuries2', ['Jewel', 'Wine', 'Spice', 'Fragrance', 'Silk', 'Fur', 'Artwork', 'Sword', 'Creature', 'Ore', 'Root', 'Scripture']]
    , ['news1', ['Duel', 'Birth', 'Market', 'Trial', 'Ritual', 'Mercenaries', 'Festival', 'Tournament', 'Punishment', 'Performance', 'Death', 'Marriage']]
    , ['news2', ['Pensive', 'Joyous', 'Content', 'Divided', 'Furious', 'Sceptical', 'Adoring', 'Nostalgic', 'Unified', 'Bleak', 'Solemn', 'Optimistic']]
    , ['woe1', ['Secretive', 'Violent', 'Looming', 'Sudden', 'Ongoing', 'Prophecised', 'Mysterious', 'Sanctioned', 'Unseen', 'Vast', 'Escalating', 'Concealed']]
    , ['woe2', ['Disease', 'Famine', 'Raids', 'Invasion', 'Abduction', 'Storm', 'Fire', 'Revolt', 'Exodus', 'Beast', 'Killing', 'Theft']]
]);

const people_sparks = new Map([
    ['ailment1', ['Hidden', 'Mild', 'Intermittent', 'Growing', 'Medicated', 'Denied', 'Unexplained', 'Constant', 'Diminishing', 'Permanent', 'Debilitating', 'Obvious']]
    , ['ailment2', ['Insomnia', 'Migraines', 'Arthritis', 'Nausea', 'Fixation', 'Blindness', 'Deafness', 'Melancholy', 'Shaking', 'Frailty', 'Coughing', 'Lethargy']]
    , ['appearance1', ['Delicate', 'Short', 'Robust', 'Hard', 'Haggard', 'Cold', 'Warm', 'Youthful', 'Soft', 'Sickly', 'Tall', 'Rough']]
    , ['appearance2', ['Armoured', 'Tattered', 'Vibrant', 'Crude', 'Eclectic', 'Traditional', 'Comfortable', 'Gaudy', 'Drab', 'Decorated', 'Functional', 'Elegant']]
    , ['background1', ['Deprived', 'Pious', 'Outcast', 'Military', 'Insular', 'Nomadic', 'Drudgery', 'Mercantile', 'Feral', 'Prestigious', 'Academic', 'Pampered']]
    , ['background2', ['War', 'Migration', 'Riding', 'Study', 'Exile', 'Joy', 'Sickness', 'Escape', 'Injury', 'Friendship', 'Execution', 'Romance']]
    , ['desire1', ['Escape', 'Wealth', 'Status', 'Knowledge', 'Mastery', 'Heirloom', 'Marriage', 'Truth', 'Travel', 'Power', 'Security', 'Forgiveness']]
    , ['desire2', ['Freedom', 'Love', 'Legacy', 'Recovery', 'Revenge', 'Duty', 'Fear', 'Guilt', 'Recognition', 'Defiance', 'Curiosity', 'Hatred']]
    , ['heraldry1', ['Light', 'Hot', 'Earthy', 'Rich', 'Metallic', 'Brilliant', 'Grey', 'Jewelled', 'Subdued', 'Airy', 'Cold', 'Dark']]
    , ['heraldry2', ['Beast', 'Bird', 'Fish', 'Weapon', 'Crown', 'Tree', 'Flower', 'Bodypart', 'Structure', 'Ring', 'Tool', 'Star']]
    , ['personality1', ['Cautious', 'Spiritual', 'Intellectual', 'Ambitious', 'Serene', 'Righteous', 'Empathetic', 'Unstable', 'Prying', 'Melancholic', 'Cynical', 'Rash']]
    , ['personality2', ['Botany', 'History', 'Music', 'Gambling', 'Animals', 'Art', 'Cookery', 'Craft', 'Fishing', 'Fashion', 'Hunting', 'Stories']]
    , ['relationship1', ['Adoring', 'Reluctant', 'Secret', 'Estranged', 'Hateful', 'Distant', 'Harmonious', 'Intimate', 'Recent', 'Sworn', 'Tumultuous', 'Resentful']]
    , ['relationship2', ['Kin', 'Friend', 'Lover', 'Spouse', 'Supporter', 'Ally', 'Rival', 'Successor', 'Mentor', 'Peer', 'Enemy', 'Guardian']]
    , ['task1', ['Investigate', 'Capture', 'Destroy', 'Transport', 'Retrieve', 'Mend', 'Break', 'Guard', 'Aid', 'Salvage', 'Conceal', 'Hunt']]
    , ['task2', ['Knight', 'Seer', 'Vassals', 'Livestock', 'Monument', 'Gold', 'Ruin', 'Animals', 'Dwelling', 'Holding', 'Bridge', 'Warband']]
    , ['voice1', ['Whispering', 'Soothing', 'Smooth', 'Flat', 'Mumbled', 'Weak', 'Strong', 'Hesitant', 'Melodic', 'Gravelly', 'Erratic', 'Booming']]
    , ['voice2', ['Formal', 'Poetic', 'Precise', 'Intense', 'Rambling', 'Detached', 'Passionate', 'Terse', 'Relaxed', 'Blunt', 'Boisterous', 'Friendly']]
]);

const combat_sparks = new Map([
    ['soldier1', ['Mobile', 'Reluctant', 'Mounted', 'Renowned', 'Zealous', 'Conscript', 'Cowardly', 'Heavy', 'Bloodthirsty', 'Fancy', 'Fearsome', 'Mercenary']]
    , ['soldier2', ['Skirmisher', 'Archer', 'Scout', 'Militia', 'Guard', 'Infiltrator', 'Raider', 'Veteran', 'Infantry', 'Rider', 'Charger', 'Knight']]
    , ['weapon1', ['Short', 'Pole', 'Chain', 'Barbed', 'Forked', 'Curved', 'Weighted', 'Double', 'Crossed', 'Throwing', 'Thin', 'Long']]
    , ['weapon2', ['Blade', 'Spear', 'Axe', 'Mace', 'Cleaver', 'Hammer', 'Spike', 'Hook', 'Club', 'Rod', 'Fang', 'Sword']]
    , ['manoeuvres1', ['Feint', 'Strike', 'Boast', 'Defend', 'Negotiate', 'Flurry', 'Rush', 'Taunt', 'Jab', 'Charge', 'Onslaught', 'Provoke']]
    , ['manoeuvres2', ['Demoralise', 'Confuse', 'Exploit', 'Stall', 'Relocate', 'Observe', 'Defeat', 'Expose', 'Surprise', 'Stagger', 'Weaken', 'Intimidate']]
    , ['conflict1', ['Border', 'Religion', 'Succession', 'Resource', 'Debt', 'Betrayal', 'Theft', 'Conquest', 'Marriage', 'Deceit', 'Waterway', 'Bloodfeud']]
    , ['conflict2', ['War', 'Raids', 'Animosity', 'Truce', 'Skirmishes', 'Standoff', 'Occupation', 'Stalemate', 'Blockade', 'Tension', 'Forgotten', 'Negotiations']]
    , ['duel1', ['Joust', 'Swords', 'Partner', 'Team', 'Unarmoured', 'Chained', 'Blood', 'Death', 'Surrender', 'Judged', 'Blunt', 'Javelins']]
    , ['duel2', ['Timed', 'Pit', 'Bridge', 'Immobile', 'Maze', 'Archers', 'Fire', 'Beasts', 'Mud', 'Night', 'Water', 'Cage']]
    , ['battlefield1', ['River', 'Ruins', 'Hill', 'Forest', 'Lake', 'Outpost', 'Pass', 'Farm', 'Trail', 'Bridge', 'Wall', 'Dwelling']]
    , ['battlefield2', ['Smoke', 'Mud', 'Flies', 'Trenches', 'Tower', 'Boulders', 'Flowers', 'Streams', 'Thorns', 'Stink', 'Ravine', 'Tombs']]
    , ['deployment1', ['Aggressive', 'Mobile', 'Tight', 'Deceptive', 'Shielded', 'Rigid', 'Flexible', 'Open', 'Focused', 'Dispersed', 'Reinforced', 'Defensive']]
    , ['deployment2', ['Line', 'Column', 'Chevron', 'Ranks', 'Square', 'Circle', 'Flank', 'Skirmish', 'Block', 'Square', 'Wedge', 'Scatter']]
    , ['strategy1', ['Encircle', 'Capture', 'Assault', 'Harass', 'Pillage', 'Outlast', 'Ambush', 'Overwhelm', 'Blockade', 'Divide', 'Focus', 'Counter']]
    , ['strategy2', ['Darkness', 'Reserves', 'Diversion', 'Betrayal', 'Artillery', 'Camouflage', 'Bluff', 'Delay', 'Decoy', 'Bait', 'Sacrifice', 'Fire']]
    , ['event1', ['Allies', 'Morale', 'Weather', 'Terrain', 'Strategy', 'Discipline', 'Animal', 'Opportunists', 'Deception', 'Leader', 'Loot', 'Weapons']]
    , ['event2', ['Collapse', 'Attack', 'Slaughter', 'Stalemate', 'Stall', 'Falter', 'Sabotage', 'Scatter', 'Charge', 'Confusion', 'Worsening', 'Discovery']]
])

const knave_locations = new Map([
    ['location2', ['Ashland ', 'Badland ', 'Bamboo forest ', 'Basalt columns ', 'Bay ', 'Beach ', 'Bluff ', 'Bog ', 'Boulder field ', 'Brook ', 'Butte ', 'Caldera ', 'Canyon ', 'Cave ', 'Cliff ', 'Cloud forest', 'Coniferous forest', 'Copse ', 'Crag ', 'Crater ', 'Creek ', 'Crossing ', 'Crystals ', 'Deciduous forest', 'Delta ', 'Dunes ', 'Dust bowl', 'Element ', 'Fen ', 'Fjord ', 'Floodplain ', 'Gas vent', 'Geyser ', 'Glacier ', 'Gorge ', 'Grotto ', 'Grove ', 'Gulch ', 'Heath ', 'Highland ', 'Hollow ', 'Hoodoo ', 'Hot ', 'Ice ', 'Jungle ', 'Knoll ', 'Lagoon ', 'Lair ', 'Lake ', 'Lakebed ', 'Lava field', 'Lava tube', 'Loch', 'Mangrove', 'Marsh', 'Meadow', 'Mesa', 'Mire', 'Moor', 'Mountain', 'Mud plain', 'Oasis', 'Oil seep', 'Pass', 'Pasture', 'Petrified', 'Pit', 'Plateau', 'Pond', 'Prairie', 'Quicksand', 'Rainforest', 'Rapids', 'Ravine', 'Ridge', 'River', 'Riverland', 'Rockslide', 'flat', 'Salt marsh', 'Savanna', 'Scree slope', 'Scrubland', 'Sinkhole', 'Spring', 'Steppe', 'Stream', 'Sulfur spring', 'Swamp', 'Taiga', 'Tar pit', 'Thicket', 'Tundra', 'Valley', 'Volcanic plain', 'Volcano', 'Wasteland', 'Waterfall', 'Wetlands', 'Whirlpool']]
    , ['structures', ['Abbey', 'Lighthouse', 'Altar', 'Logging camp', 'Amphitheater', 'Manor', 'Aqueduct', 'Market', 'Archive', 'Memorial', 'Asylum', 'Mill', 'Bandit camp', 'Mine', 'Barn', 'Monastery', 'Battlefield', 'Monolith', 'Bell tower', 'Monument', 'Bonfire', 'Mule track', 'Bower', 'Obelisk', 'Brazier', 'Orchard', 'Outpost', 'Cairn', 'Paved road', 'Cart track', 'Pen', 'Castle', 'Pilgrim camp', 'Catacomb', 'Pillar', 'Chapel', 'Port', 'City', 'Prison', 'Cistern', 'Pyramid', 'Convent', 'Refugee camp', 'Crossroads', 'Road', 'Dam', 'Dirt road', 'Ruin', 'Dolmen', 'Shepherd hut', 'Shrine', 'Farm', 'Signal tower', 'Ferry', 'Stable', 'Festival', 'Statue', 'Fishing hut', 'Stone bridge', 'Ford', 'Stone circle', 'Forester lodge', 'Surveyor camp', 'Fort', 'Tavern', 'Gallows', 'Temple', 'Garden', 'Toll house', 'Garrison', 'Tomb', 'Gate', 'Tower', 'Gibbet', 'Town', 'Graveyard', 'Trader camp', 'Hamlet', 'Trail', 'Henge', 'Hermitage', 'Village', 'Hideout', 'Wall', 'Highway', 'Watchtower', 'Hunter’s camp', 'Watermill', 'Hunting lodge', 'Well', 'Windmill', 'Keep', 'Wizard tower', 'Library', 'Wooden bridge']]
    , ['place_traits1', ['Ashen', 'Loathsome', 'Bewitching', 'Mechanical', 'Black', 'Misty', 'Blessed', 'Murmuring', 'Blighted', 'Mysterious', 'Bloody', 'Oozing', 'Boiling', 'Overgrown', 'Bright', 'Perilous', 'Broken', 'Petrified', 'Buried', 'Phantasmal', 'Burning', 'Phasing', 'Charred', 'Pristine', 'Collapsed', 'Ravaged', 'Crawling', 'Ravenous', 'Crimson', 'Restless', 'Crumbling', 'Revered', 'Crystalline', 'Cursed', 'Savage', 'Dark', 'Scorching', 'Dead', 'Screaming', 'Desolate', 'Shadowy', 'Disorienting', 'Shifting', 'Divine', 'Shivering', 'Doomed', 'Shrouded', 'Echoing', 'Silent', 'Eerie', 'Singing', 'Sinister', 'Elder', 'Sinking', 'Eldritch', 'Sleeping', 'Endless', 'Stony', 'Filthy', 'Sunken', 'Flooded', 'Swamped', 'Forbidden', 'Swarming', 'Forgotten', 'Sweltering', 'Frozen', 'Terrifying', 'Ghostly', 'Glittering', 'Thorny', 'Gloomy', 'Thundering', 'Grim', 'Twisting', 'Haunted', 'Unquiet', 'Hidden', 'Vandalized', 'Holy', 'Vast', 'Humid', 'Watching', 'Infernal', 'Whispering', 'Infested', 'Windy', 'Jagged', 'Withered', 'Labyrinthine', 'Wondrous', 'Living', 'Writhing']]
    , ['place_traits2', ['Ashen', 'Loathsome', 'Bewitching', 'Mechanical', 'Black', 'Misty', 'Blessed', 'Murmuring', 'Blighted', 'Mysterious', 'Bloody', 'Oozing', 'Boiling', 'Overgrown', 'Bright', 'Perilous', 'Broken', 'Petrified', 'Buried', 'Phantasmal', 'Burning', 'Phasing', 'Charred', 'Pristine', 'Collapsed', 'Ravaged', 'Crawling', 'Ravenous', 'Crimson', 'Restless', 'Crumbling', 'Revered', 'Crystalline', 'Cursed', 'Savage', 'Dark', 'Scorching', 'Dead', 'Screaming', 'Desolate', 'Shadowy', 'Disorienting', 'Shifting', 'Divine', 'Shivering', 'Doomed', 'Shrouded', 'Echoing', 'Silent', 'Eerie', 'Singing', 'Sinister', 'Elder', 'Sinking', 'Eldritch', 'Sleeping', 'Endless', 'Stony', 'Filthy', 'Sunken', 'Flooded', 'Swamped', 'Forbidden', 'Swarming', 'Forgotten', 'Sweltering', 'Frozen', 'Terrifying', 'Ghostly', 'Glittering', 'Thorny', 'Gloomy', 'Thundering', 'Grim', 'Twisting', 'Haunted', 'Unquiet', 'Hidden', 'Vandalized', 'Holy', 'Vast', 'Humid', 'Watching', 'Infernal', 'Whispering', 'Infested', 'Windy', 'Jagged', 'Withered', 'Labyrinthine', 'Wondrous', 'Living', 'Writhing']]
    , ['place_traits3', ['Ashen', 'Loathsome', 'Bewitching', 'Mechanical', 'Black', 'Misty', 'Blessed', 'Murmuring', 'Blighted', 'Mysterious', 'Bloody', 'Oozing', 'Boiling', 'Overgrown', 'Bright', 'Perilous', 'Broken', 'Petrified', 'Buried', 'Phantasmal', 'Burning', 'Phasing', 'Charred', 'Pristine', 'Collapsed', 'Ravaged', 'Crawling', 'Ravenous', 'Crimson', 'Restless', 'Crumbling', 'Revered', 'Crystalline', 'Cursed', 'Savage', 'Dark', 'Scorching', 'Dead', 'Screaming', 'Desolate', 'Shadowy', 'Disorienting', 'Shifting', 'Divine', 'Shivering', 'Doomed', 'Shrouded', 'Echoing', 'Silent', 'Eerie', 'Singing', 'Sinister', 'Elder', 'Sinking', 'Eldritch', 'Sleeping', 'Endless', 'Stony', 'Filthy', 'Sunken', 'Flooded', 'Swamped', 'Forbidden', 'Swarming', 'Forgotten', 'Sweltering', 'Frozen', 'Terrifying', 'Ghostly', 'Glittering', 'Thorny', 'Gloomy', 'Thundering', 'Grim', 'Twisting', 'Haunted', 'Unquiet', 'Hidden', 'Vandalized', 'Holy', 'Vast', 'Humid', 'Watching', 'Infernal', 'Whispering', 'Infested', 'Windy', 'Jagged', 'Withered', 'Labyrinthine', 'Wondrous', 'Living', 'Writhing']]
    , ['place_traits4', ['Ashen', 'Loathsome', 'Bewitching', 'Mechanical', 'Black', 'Misty', 'Blessed', 'Murmuring', 'Blighted', 'Mysterious', 'Bloody', 'Oozing', 'Boiling', 'Overgrown', 'Bright', 'Perilous', 'Broken', 'Petrified', 'Buried', 'Phantasmal', 'Burning', 'Phasing', 'Charred', 'Pristine', 'Collapsed', 'Ravaged', 'Crawling', 'Ravenous', 'Crimson', 'Restless', 'Crumbling', 'Revered', 'Crystalline', 'Cursed', 'Savage', 'Dark', 'Scorching', 'Dead', 'Screaming', 'Desolate', 'Shadowy', 'Disorienting', 'Shifting', 'Divine', 'Shivering', 'Doomed', 'Shrouded', 'Echoing', 'Silent', 'Eerie', 'Singing', 'Sinister', 'Elder', 'Sinking', 'Eldritch', 'Sleeping', 'Endless', 'Stony', 'Filthy', 'Sunken', 'Flooded', 'Swamped', 'Forbidden', 'Swarming', 'Forgotten', 'Sweltering', 'Frozen', 'Terrifying', 'Ghostly', 'Glittering', 'Thorny', 'Gloomy', 'Thundering', 'Grim', 'Twisting', 'Haunted', 'Unquiet', 'Hidden', 'Vandalized', 'Holy', 'Vast', 'Humid', 'Watching', 'Infernal', 'Whispering', 'Infested', 'Windy', 'Jagged', 'Withered', 'Labyrinthine', 'Wondrous', 'Living', 'Writhing']]
    , ['rooms', ['Alchemy room', 'Junk room', 'Alcohol cellar', 'Kennel', 'Arboretum', 'Kitchen', 'Archery range', 'Laboratory', 'Arena', 'Lair', 'Armory', 'Larder', 'Arsenal', 'Latrine', 'Art gallery', 'Library', 'Art studio', 'Lounge', 'Audience hall', 'Map room', 'Aviary', 'Maze', 'Ballroom', 'Banquet hall', 'Meditation room', 'Barracks', 'Menagerie', 'Baths', 'Mess hall', 'Bed chamber', 'Mews', 'Brewery', 'Museum', 'Music room', 'Catacombs', 'Nursery', 'Cave', 'Observatory', 'Cell', 'Pantry', 'Chapel', 'Parlor', 'Chasm', 'Pit', 'Church', 'Poison room', 'Cistern', 'Pool', 'Cloakroom', 'Prison', 'Concert hall', 'Record room', 'Conjuring Room', 'Courtroom', 'Salon', 'Courtyard', 'Scriptorium', 'Crematorium', 'Scullery', 'Crypt', 'Sculpture gallery', 'Dining room', 'Shop', 'Divination room', 'Shrine', 'Dormitory', 'Slaughterhouse', 'Smoking Room', 'Dressing room', 'Stables', 'Embalming room', 'Storeroom', 'Fighting pit', 'Fissure', 'Study', 'Forge', 'Tapestry room', 'Fountain room', 'Theater', 'Gallery', 'Throne room', 'Game room', 'Torture room', 'Garden', 'Training hall', 'Gatehouse', 'Treasury', 'Great hall', 'Trophy room', 'Guardroom', 'Vault', 'Hall', 'Work pit', 'Infirmary', 'Workshop']]
    , ['room_details', ['Alcohol', 'Map', 'Alcove', 'Altar', 'Message', 'Balcony', 'Mine cart', 'Bars', 'Mirror', 'Bas-relief', 'Bath', 'Bed', 'Mural', 'Bones', 'Nest', 'Painting', 'Brazier', 'Pews', 'Broken glass', 'Pillar', 'Cabinet', 'Pipes', 'Cage', 'Pool', 'Carpet', 'Portcullis', 'Carvings', 'Cauldron', 'Refuse pile', 'Chains', 'Repairs', 'Chalk marks', 'Roots', 'Chandelier', 'Rubble', 'Chest', 'Shaft', 'Coffin', 'Shelf', 'Coins', 'Collapsed ceiling', 'Skeletons', 'Collapsed floor', 'Smoke', 'Collapsed walls', 'Sofa', 'Crawlspace', 'Crumbling ceiling', 'Spyhole', 'Crumbling floors', 'Stairs', 'Crumbling walls', 'Stalactites', 'Curtain', 'Statues', 'Dais', 'Stove', 'Dishes', 'Display case', 'Dumbwaiter', 'Table', 'Elevator', 'Tapestry', 'Thick dust', 'Fireplace', 'Throne', 'Flowing water', 'Toilet', 'Fountain', 'Fungi', 'Torture device', 'Graffiti', 'Training dummy', 'Trapdoor', 'Incense', 'Vines', 'Instrument', 'Wardrobe', 'Lantern']]
    , ['room_themes', ['Mouths', 'Blessings', 'Music', 'Blindness', 'Mutation', 'Blood', 'Outsiders', 'Bones', 'Pageantry', 'Paranoia', 'Brains', 'Chaos', 'Poison', 'Priests', 'Collapse', 'Prophecy', 'Combat', 'Rats', 'Corpses', 'Refugees', 'Corruption', 'Restless dead', 'Creation', 'Revenge', 'Criminal activity', 'Riches', 'Crows', 'Rituals', 'Cults', 'Rival factions', 'Curses', 'Sacrifice', 'Death', 'Savage fury', 'Decay', 'Secret knowledge', 'Disease', 'Serpents', 'Divination', 'Shadows', 'Skulls', 'Dragons', 'Slavery', 'Drowning', 'Slime', 'Eyes', 'Smoke', 'Songs', 'Souls', 'Faces', 'Spiders', 'Feasting', 'Stasis', 'Fog', 'Statues', 'Gateways', 'Summoning', 'Ghosts', 'Survival', 'Gods', 'Teeth', 'Hands', 'Tentacles', 'Holy war', 'Tests and trials', 'Hunger', 'The moon', 'Hunting', 'The stars', 'Imprisonment', 'The sun', 'Invasion', 'Thorns', 'Invention', 'Trickery', 'Inversion', 'Tyranny', 'Vampires', 'Judgment', 'Water', 'Light', 'Wild growth', 'Locks', 'Wine', 'Madness', 'Winter', 'Wolves', 'Memory', 'Worms', 'Mirrors', 'Zealotry']]
    , ['dungeons', ['Alchemy lab', 'Lava tubes', 'Animal burrow', 'Library', 'Aquarium', 'Living dungeon', 'Arboretum', 'Lock', 'Archive', 'Mansion', 'Arena', 'Marketplace', 'Armory', 'Mausoleum', 'Art gallery', 'Memorial', 'Asylum', 'Menagerie', 'Automaton', 'Mill', 'Aviary', 'Mine', 'Bank', 'Monastery', 'Bathhouse', 'Monster gallery', 'Monster lab', 'Bunker', 'Monster lair', 'Casino', 'Museum', 'Castle', 'Mushroom forest', 'Catacombs', 'Nest', 'Cathedral', 'Nursery', 'Cave system', 'Observatory', 'Cistern', 'Orrery', 'City', 'Palace', 'Clock', 'Prison', 'Corpse', 'Race track', 'Court', 'Criminal den', 'Sanctum', 'Curiosity cabinet', 'Sculpture gallery', 'Dam', 'Sewer', 'Deathtrap', 'Ship', 'Depot', 'Silo', 'Dig site', 'Slaughterhouse', 'Dormitory', 'Stable', 'Faction hideout', 'Stronghold', 'Factory', 'Fashion gallery', 'Summoning site', 'Feasting hall', 'Temple', 'Forge', 'Testing ground', 'Garbage pit', 'Theater', 'Gateway', 'Theme park', 'Guildhall', 'Tomb', 'Historical gallery', 'Tower', 'Hospital', 'Training complex', 'Hotel', 'Treasure vault', 'Ice caves', 'Tree', 'Insect hive', 'Warehouse', 'Instrument', 'Warren', 'Kennel', 'Waterworks', 'Kitchen', 'Weapon gallery', 'Labyrinth', 'Wine cellar', 'Larder', 'Work pit']]
]);

const knave_magic = new Map([
    ['qualities', ['Abnormal', 'Loathsome', 'Abominable', 'Magnificent', 'Advanced', 'Majestic', 'Ancestral', 'Marvelous', 'Ancient', 'Masterful', 'Arcane', 'Miraculous', 'Artful', 'Mysterious', 'Baleful', 'Noetic', 'Bizarre', 'Noxious', 'Canonical', 'Odious', 'Celestial', 'Ominous', 'Cerebral', 'Original', 'Chaotic', 'Orthodox', 'Ostentatious', 'Cosmic', 'Otherworldly', 'Crafty', 'Peculiar', 'Cryptic', 'Pernicious', 'Curious', 'Phenomenal', 'Detestable', 'Dismal', 'Planar', 'Dreadful', 'Planetary', 'Elder', 'Preeminent', 'Eldritch', 'Primal', 'Enigmatic', 'Primeval', 'Esoteric', 'Primordial', 'Excellent', 'Prodigious', 'Exquisite', 'Psychedelic', 'Extraordinary', 'Remarkable', 'Fantastic', 'Resplendent', 'Fey', 'Royal', 'Foul', 'Sacred', 'Galactic', 'Ghastly', 'Sinister', 'Grand', 'Grim', 'Splendid', 'Grotesque', 'Subtle', 'Hateful', 'Superior', 'Hideous', 'Supreme', 'Horrible', 'Incomparable', 'Incomprehensible', 'True', 'Inexplicable', 'Uncanny', 'Infernal', 'Unfathomable', 'Ingenious', 'Unnatural', 'Inscrutable', 'Unorthodox', 'Insidious', 'Unspeakable', 'Iridescent', 'Vile', 'Jocular', 'Whimsical', 'Lawful', 'Wondrous', 'Legendary', 'Wretched']]
    , ['effects', ['Absorbing', 'Infecting', 'Accelerating', 'Intoxicating', 'Irradiating', 'Amusing', 'Irritating', 'Animating', 'Levitating', 'Armoring', 'Liquefying', 'Attracting', 'Maddening', 'Avenging', 'Menacing', 'Awakening', 'Mending', 'Banishing', 'Mesmerizing', 'Beautifying', 'Mindreading', 'Bewildering', 'Mocking', 'Binding', 'Monitoring', 'Blinding', 'Multiplying', 'Blossoming', 'Mutating', 'Burning', 'Nauseating', 'Charming', 'Nullifying', 'Cleansing', 'Pacifying', 'Commanding', 'Persuading', 'Communicating', 'Petrifying', 'Concealing', 'Piercing', 'Condemning', 'Preserving', 'Corroding', 'Pummeling', 'Corrupting', 'Putrefying', 'Crushing', 'Reflecting', 'Darkening', 'Refreshing', 'Dazzling', 'Regenerating', 'Deafening', 'Repelling', 'Deciphering', 'Retrieving', 'Diminishing', 'Revealing', 'Disguising', 'Saddening', 'Dispelling', 'Sanctifying', 'Draining', 'Scrying', 'Duplicating', 'Sealing', 'Electrifying', 'Shielding', 'Emboldening', 'Silencing', 'Enraging', 'Slicing', 'Enticing', 'Spawning', 'Etherealizing', 'Stinging', 'Excruciating', 'Strangling', 'Expanding', 'Summoning', 'Foreseeing', 'Teleporting', 'Freezing', 'Terrifying', 'Fusing', 'Transmuting', 'Hardening', 'Haunting', 'Transporting', 'Healing', 'Vaporizing', 'Identifying', 'Warding', 'Illuminating', 'Wearying', 'Imprisoning', 'Withering']]
    , ['elements', ['Acid', 'Amber', 'Memory', 'Ash', 'Miasma', 'Beer', 'Moss', 'Bile', 'Mud', 'Blood', 'Nectar', 'Blossom', 'Oatmeal', 'Bone', 'Obsidian', 'Brass', 'Oil', 'Brimstone', 'Paint', 'Brine', 'Paper', 'Butter', 'Perfume', 'Chalk', 'Plague', 'Chaos', 'Poison', 'Clay', 'Pollen', 'Cloud', 'Quicksilver', 'Cold', 'Radiation', 'Crystal', 'Rain', 'Darkness', 'Root', 'Death', 'Rot', 'Salt', 'Dream', 'Sand', 'Dust', 'Sap', 'Shadow', 'Flame', 'Silk', 'Flesh', 'Slime', 'Foam', 'Smoke', 'Fog', 'Snow', 'Soot', 'Frost', 'Spark', 'Fume', 'Speed', 'Fungus', 'Spore', 'Ghost', 'Steam', 'Glass', 'Stench', 'Glue', 'Stone', 'Gravel', 'Storm', 'Hail', 'Sugar', 'Heat', 'Syrup', 'Honey', 'Taffy', 'Ice', 'Tar', 'Incense', 'Tea', 'Ink', 'Tears', 'Iron', 'Thorn', 'Ivory', 'Vine', 'Lava', 'Void', 'Lead', 'Water', 'Leaf', 'Wax', 'Light', 'Wind', 'Lightning', 'Wine', 'Marmalade', 'Wood']]
    , ['forms', ['Key', 'Arc', 'Knife', 'Archer', 'Knight', 'Armor', 'Mask', 'Arrow', 'Aura', 'Avalanche', 'Monolith', 'Axe', 'Beacon', 'Mouth', 'Beam', 'Beast', 'Path', 'Blade', 'Pit', 'Blast', 'Pool', 'Blob', 'Pulse', 'Bolt', 'Pyramid', 'Bubble', 'Ray', 'Cage', 'Rune', 'Carriage', 'Sanctuary', 'Chain', 'Serpent', 'Chariot', 'Servant', 'Circle', 'Shield', 'Cloak', 'Skeleton', 'Skin', 'Cloud', 'Song', 'Coil', 'Spear', 'Colossus', 'Sphere', 'Column', 'Spider', 'Cone', 'Spike', 'Crown', 'Spray', 'Cube', 'Staff', 'Disk', 'Steed', 'Dragon', 'Storm', 'Eye', 'Strike', 'Fang', 'Finger', 'Fissure', 'Tangle', 'Fist', 'Flood', 'Torrent', 'Fly', 'Touch', 'Fountain', 'Tree', 'Gate', 'Tunnel', 'Gaze', 'Vortex', 'Geyser', 'Wall', 'Gloves', 'Wave', 'Guardian', 'Hammer', 'Web', 'Hand', 'Wheel', 'Hawk', 'Whip', 'Horn', 'Word', 'Hound', 'Zone']]
    , ['delusions', ['Invisible', 'Always drunk', 'Invisible servant', 'Always polite', 'Invulnerable', 'Always rude', 'Language switch', 'Always sleepy', 'Amnesia', 'Medium', 'Mind controlled', 'Aura reading', 'Missing limb', 'Automaton', 'Being followed', 'Cannot count', 'Cannot lie', 'Must dance', 'Cannot read', 'Must lie', 'Chosen one', 'Must obey', 'Clone', 'Must shout', 'Constant rage', 'Must skip', 'Dark vision', 'Must steal', 'Demonic', 'Divine', 'Extra limb', 'Falls in love', 'Personal army', 'Famous', 'Fears birds', 'Planar traveler', 'Fears blood', 'Fears fire', 'Prophet', 'Fears gold', 'Reincarnated', 'Fears iron', 'Rich', 'Fears music', 'Says thoughts', 'Fears own hand', 'Secret monarch', 'Fears PC', 'Sees dead people', 'Fears rain', 'Shapeshifter', 'Fears rivers', 'Silent', 'Fears sleep', 'Fears sunlight', 'Spy', 'Fears the moon', 'Super strength', 'Flight', 'Talks to animals', 'Genius', 'Talks to plants', 'Gets lost', 'Telekinetic', 'Telepathic', 'Gorgeous', 'Time traveler', 'Hates violence', 'Vampire', 'Healing touch', 'Hideous', 'Weather control', 'Illuminati', 'Werewolf', 'Immortal', 'Whispers', 'In an RPG', 'Infamous', 'X-ray vision']]
    , ['disasters', ['Acid rain', 'Language loss', 'Aging accelerates', 'Lightning storm', 'Aging reverses', 'Living nightmare', 'All iron rusts', 'Locusts', 'Amnesia', 'Maggots', 'Animal revolt', 'Magic barrier', 'Animals die', 'Mass blindness', 'Animals mutate', 'Mass hypnosis', 'Animals speak', 'Mass insanity', 'Birds attack', 'Mass possession', 'Birds die', 'Mass slumber', 'Body swaps', 'Mass telepathy', 'Cities move', 'Meteor strike', 'City appears', 'Mirages', 'City changes', 'Mirrors speak', 'Deadly fog', 'No stars', 'Demon invasion', 'Objects animate', 'Doors lock', 'Outsider enters', 'Dragon wakes', 'People shrink', 'Dream plague', 'People vanish', 'Drought', 'Pits open', 'Earth to sand', 'Plague', 'Earthquake', 'Planar overlay', 'Plants wither', 'Portal opens', 'Endless day', 'Rage epidemic', 'Endless night', 'Rampant growth', 'Endless rain', 'Rifts open', 'Endless storm', 'Rivers move', 'Endless twilight', 'Rivers reverse', 'Endless winter', 'Roads move', 'Eruption', 'Shadows detach', 'Fae return', 'Shadows speak', 'Famine', 'Smoke', 'Fear epidemic', 'Space distorts', 'Firestorm', 'Stone to flesh', 'Fish die', 'Stones speak', 'Fish speak', 'Flesh to stone', 'Time loop', 'Flood', 'Time slows', 'Forest appears', 'Time warp', 'Forgetfulness', 'Tornado', 'Giants march', 'Total silence', 'Gold to tin', 'Tower appears', 'Graves open', 'Trees march', 'Gravity decreases', 'Voices of dead', 'Gravity increases', 'Water to blood', 'Hills move', 'Iron to cloth', 'Windstorm']]
    , ['magic_schools', ['Abjuration', 'Lightning', 'Air', 'Martial arts', 'Alchemy', 'Memory', 'Alteration', 'Metamagic', 'Animation', 'Mind control', 'Anti-magic', 'Mirrors', 'Archery', 'Misdirection', 'Architecture', 'Mist', 'Armor', 'Music', 'Artifice', 'Necromancy', 'Beasts', 'Oratory', 'Biomancy', 'Outsiders', 'Birds', 'Planes', 'Portals', 'Charms', 'Power', 'Chromatic', 'Protection', 'Conjuration', 'Rays', 'Counterspells', 'Reptiles', 'Creation', 'Revelation', 'Darkness', 'Death', 'Sea', 'Desert', 'Servants', 'Destruction', 'Shadow', 'Divination', 'Shaping', 'Sight', 'Dragons', 'Sound', 'Dreams', 'Speed', 'Earth', 'Stars', 'Emotions', 'Stasis', 'Enchantment', 'Staves', 'Evocation', 'Stealth', 'Fear', 'Stones', 'Finding', 'Storms', 'Fire', 'Summoning', 'Fish', 'Sun', 'Flight', 'Swords', 'Food', 'Telekinesis', 'Force', 'Telepathy', 'Forest', 'Teleportation', 'Fungi', 'Theft', 'Geometry', 'Time', 'Healing', 'Transmutation', 'Ice', 'Trickery', 'Ignorance', 'Vampirism', 'Illness', 'Walls', 'Illumination', 'Water', 'Illusion', 'Weapons', 'Insects', 'Wild magic', 'Invocation', 'Wind', 'Knowledge', 'Witchery']]
    , ['domains', ['Acid', 'Mountains', 'Alchemy', 'Murderers', 'Beauty', 'Music', 'Bees', 'Oratory', 'Beggars', 'Performance', 'Betrayal', 'Poison', 'Birds', 'Priests', 'Blades', 'Prisoners', 'Blood', 'Rage', 'Blossoms', 'Rain', 'Revenge', 'Clay', 'Revolution', 'Clouds', 'Roads', 'Commerce', 'Courage', 'Royalty', 'Cowards', 'Rust', 'Craftsmanship', 'Sand', 'Crows', 'Secrets', 'Darkness', 'Serpents', 'Deserts', 'Silence', 'Destruction', 'Slaves', 'Disease', 'Sleep', 'Doors', 'Smoke', 'Dreams', 'Soldiers', 'Duels', 'Spiders', 'Eagles', 'Swamps', 'Earthquakes', 'Tailors', 'Fire', 'The blind', 'Fish', 'The elderly', 'Forge', 'The future', 'Fungi', 'The grave', 'Gluttony', 'The harvest', 'Greed', 'The hearth', 'Healing', 'The hunt', 'Horses', 'The law', 'Hunger', 'The sea', 'Illusions', 'Thieves', 'Jealousy', 'Thorns', 'Language', 'Travelers', 'Lava', 'Trees', 'Libraries', 'Trickery', 'Light', 'Truth', 'Lightning', 'Tundra', 'Love', 'Tunnels', 'Luck', 'Vermin', 'Machines', 'Walls', 'Madness', 'Wind', 'Wine', 'Mazes', 'Winter', 'Mirrors', 'Wolves']]
    , ['symbols', ['Key', 'Antlers', 'Knot', 'Arrow', 'Lamp', 'Axe', 'Leaf', 'Bear', 'Lightning bolt', 'Bell', 'Lock', 'Bird', 'Mask', 'Blood drop', 'Book', 'Moon', 'Boots', 'Nut', 'Bow', 'Octopus', 'Bowl', 'Branch', 'Ox', 'Brazier', 'Pen', 'Cauldron', 'Pincer', 'Chain', 'Pine cone', 'Chariot', 'Planet', 'Circle', 'Rabbit', 'Rat', 'Cloud', 'Ring', 'Coin', 'Scorpion', 'Constellation', 'Scales', 'Crab', 'Scroll', 'Cross', 'Serpent', 'Crown', 'Shield', 'Crystal', 'Sickle', 'Dagger', 'Skull', 'Deer', 'Snail', 'Dice', 'Snowflake', 'Eye', 'Spear', 'Fangs', 'Spiral', 'Feather', 'Square', 'Fish', 'Staff', 'Fist', 'Star', 'Flower', 'Sun', 'Fountain', 'Sword', 'Tentacle', 'Throne', 'Fox', 'Tooth', 'Frog', 'Torch', 'Gate', 'Tree', 'Goat', 'Triangle', 'Hammer', 'Turtle', 'Hand', 'Wave', 'Heart', 'Helmet', 'Web', 'Hook', 'Whale', 'Horn', 'Whip', 'Horse', 'Wings', 'Hourglass', 'Wolf']]
]);

const knave_extras = new Map([
    ['activities', ['Ambushing', 'Harvesting', 'Arguing', 'Hauling', 'Awarding', 'Healing', 'Beautifying', 'Hiding', 'Befouling', 'Igniting', 'Begging', 'Infiltrating', 'Besieging', 'Initiating', 'Birthing', 'Instructing', 'Blessing', 'Kidnapping', 'Brawling', 'Looting', 'Building', 'Mapping', 'Burgling', 'Marrying', 'Burying', 'Camping', 'Mourning', 'Capturing', 'Murdering', 'Carving', 'Pardoning', 'Celebrating', 'Parleying', 'Chasing', 'Patrolling', 'Cleaning', 'Performing', 'Clearing', 'Planning', 'Climbing', 'Planting', 'Collecting', 'Playing', 'Competing', 'Praying', 'Convening', 'Preaching', 'Cooking', 'Processing', 'Courting', 'Questioning', 'Crafting', 'Repairing', 'Cursing', 'Rescuing', 'Dancing', 'Resting', 'Defacing', 'Rioting', 'Defending', 'Robbing', 'Delivering', 'Sacrificing', 'Destroying', 'Scavenging', 'Dousing', 'Scouting', 'Dueling', 'Searching', 'Dying', 'Selling', 'Eating', 'Singing', 'Sleeping', 'Escaping', 'Escorting', 'Summoning', 'Excavating', 'Surrendering', 'Executing', 'Swindling', 'Feasting', 'Fighting', 'Tending', 'Fleeing', 'Threatening', 'Foraging', 'Tracking', 'Fortifying', 'Trading', 'Gambling', 'Training', 'Traveling', 'Guarding', 'Worshiping']]
    , ['textures', ['Aerated', 'Mashed', 'Battery', 'Metallic', 'Blended', 'Motes', 'Boiling', 'Moving', 'Brackish', 'Muddy', 'Bubbling', 'Murky', 'Buttery', 'Mushy', 'Caramelized', 'Oily', 'Chalky', 'Oozy', 'Chilled', 'Pasty', 'Chunky', 'Powdery', 'Churning', 'Pudding', 'Clotted', 'Pulpy', 'Coagulated', 'Pulsing', 'Condensed', 'Pureed', 'Congealed', 'Quicksilver', 'Cool', 'Reflective', 'Creamy', 'Rippling', 'Crystalized', 'Roiling', 'Curdled', 'Sandy', 'Dregs', 'Sappy', 'Effervescent', 'Scalding', 'Filmy', 'Scummy film', 'Fizzing', 'Sediment', 'Flakes', 'Shining', 'Foaming', 'Silty', 'Foggy', 'Simmering', 'Frigid', 'Sizzling', 'Frosty', 'Slimy', 'Frothy', 'Slushy', 'Gelatinous', 'Smoking', 'Glimmering', 'Smoky', 'Gloppy', 'Soapy', 'Glowing', 'Sparkling', 'Gluey', 'Steaming', 'Grainy', 'Sticky', 'Greasy', 'Swirling', 'Gritty', 'Syrupy', 'Grounds', 'Tarry', 'Gummy', 'Thin', 'Gunky', 'Throbbing', 'Gurgling', 'Trembling', 'Hissing', 'Turbulent', 'Humming', 'Vibrating', 'Ichorous', 'Viscid', 'Icy', 'Viscous', 'Jellied', 'Warm', 'Living', 'Watery', 'Lukewarm', 'Whirling', 'Lumpy', 'Whistling']]
    , ['tastes', ['Absinthe', 'Licorice', 'Allspice', 'Lime', 'Almond', 'Loam', 'Ammonia', 'Maple syrup', 'Mead', 'Asparagus', 'Milk', 'Basil', 'Mineral', 'Beer', 'Mint', 'Berries', 'Mud', 'Black currant', 'Mustard', 'Blackberry', 'Nutmeg', 'Blood', 'Oak', 'Butter', 'Olive oil', 'Camphor', 'Onion', 'Candy', 'Orange', 'Caramel', 'Oregano', 'Cardamom', 'Peach', 'Cherry', 'Pears', 'Chili pepper', 'Pepper', 'Chives', 'Phlegm', 'Chocolate', 'Pickle juice', 'Cinnamon', 'Pine', 'Cloves', 'Pistachios', 'Coconut', 'Plum', 'Coffee', 'Pumpkin', 'Copper', 'Quince', 'Cranberry', 'Rhubarb', 'Crude oil', 'Roast duck', 'Cucumber', 'Rose', 'Cumin', 'Rosemary', 'Curry', 'Rust', 'Dates', 'Saffron', 'Elderberry', 'Sage', 'Figs', 'Salt water', 'Flowers', 'Soap', 'Garlic', 'Soursop', 'Ginger', 'Spearmint', 'Gooseberry', 'Sulphur', 'Grapefruit', 'Tamarind', 'Grass', 'Tea', 'Herbs', 'Tears', 'Honey', 'Thyme', 'Honeysuckle', 'Tobacco', 'Horseradish', 'Vanilla', 'Huckleberry', 'Walnuts', 'Hyacinth', 'Whiskey', 'Leather', 'Wine', 'Lemon', 'Wintergreen', 'Lemongrass', 'Wormwood']]
    , ['colors', ['Acid green', 'Lavender', 'Alabaster', 'Lilac', 'Amber', 'Lime', 'Amethyst', 'Magenta', 'Apricot', 'Mahogany', 'Aquamarine', 'Maroon', 'Asparagus', 'Mauve', 'Auburn', 'Milk white', 'Aureolin', 'Moss green', 'Avocado', 'Mustard', 'Azure', 'Ochre', 'Baby blue', 'Olive', 'Beige', 'Opalescent', 'Bone', 'Oxblood', 'Bottle green', 'Pea green', 'Bronze', 'Peach', 'Bubblegum', 'Peacock blue', 'Carmine', 'Pearl', 'Carrot', 'Periwinkle', 'Celadon', 'Pine green', 'Cerise', 'Plum', 'Cerulean', 'Primrose', 'Champagne', 'Pumpkin', 'Charcoal', 'Rainbow', 'Chartreuse', 'Rose', 'Chestnut', 'Ruby', 'Cinnamon', 'Russet', 'Colorless', 'Rusty', 'Coppery', 'Saffron', 'Coral pink', 'Salmon', 'Creamy', 'Sapphire', 'Crimson', 'Scarlet', 'Cyan', 'Sepia', 'Dove grey', 'Shocking pink', 'Dun', 'Silver', 'Eggshell', 'Slate blue', 'Electric blue', 'Smokey grey', 'Emerald', 'Tangerine', 'Flesh', 'Teal', 'Fuchsia', 'Terracotta', 'Fuligin', 'Titian red', 'Golden', 'Tomato', 'Grape juice', 'Turquoise', 'Heliotrope', 'Tyrian', 'Ice blue', 'Ultramarine', 'Indigo', 'Umber', 'Inky', 'Verdigris', 'Invisible', 'Vermilion', 'Ivory', 'Violet', 'Kelly green', 'Viridian']]
    , ['ingredients', ['Meadowsweet', 'Antimony', 'Arsenic', 'Mistletoe', 'Belladonna', 'Monk\'s vow', 'Bitumen', 'Black pearl', 'Moonflower', 'Blind eye', 'Mugwort', 'Natron', 'Brimstone', 'Nectar', 'Camphor', 'Nettle', 'Celandine', 'Newborn\'s cry', 'Chalk', 'Nickel', 'Nightshade', 'Cobalt', 'Cocklebur', 'Platinum', 'Coffin nail', 'Poppy', 'Columbine', 'Copper', 'Pyre ember', 'Corpse\'s hair', 'Queen bee', 'Crossroad dust', 'Queen\'s blood', 'Dandelion', 'Quicksilver', 'Deathcap', 'Ragwort', 'Devil\'s trumpet', 'Resin', 'Element', 'Rosemary', 'Sage', 'Sea water', 'Foxglove', 'Ship\'s barnacle', 'Funeral wine', 'Silver', 'Gold', 'Snakeweed', 'Grave dust', 'Soot', 'Hellebore', 'Star-metal', 'Hemlock', 'Stinkhorn', 'Henbane', 'Sugar', 'Holly', 'Thief\'s finger', 'Honey', 'Thistle', 'Hyssop', 'Tin', 'Iron', 'Tomb flower', 'Killer\'s hand', 'King\'s tooth', 'Larkspur', 'Valerian', 'Last breath', 'Verdigris', 'Lead', 'Vinegar', 'Liar’s tongue', 'Wax', 'Lightning bolt', 'Lime', 'Wedding ring', 'Lodestone', 'Widow\'s tears', 'Lotus', 'Witch hazel', 'Lye', 'Wizard\'s skull', 'Mandrake', 'Wolfsbane', 'Wormwood']]
    , ['tools', ['Acid vial', 'Iron tongs', 'Animal scent', 'Lantern', 'Antitoxin', 'Large sack', 'Astrolabe', 'Lockpicks', 'Bandoleer', 'Lodestone', 'Bear trap', 'Magnifying lens', 'Bedroll', 'Manacles', 'Beeswax', 'Marbles', 'Bell', 'Metal File', 'Bellows', 'Mortar and pestle', 'Birdcage', 'Mule', 'Blank book', 'Net', 'Blanket', 'Padlock and key', 'Block and tackle', 'Pen and ink', 'Boltcutters', 'Pickaxe', 'Bottle', 'Pitchfork', 'Bucket', 'Piton', 'Bullseye lantern', 'Pliers', 'Caltrops', 'Poison', 'Candle', 'Censer', 'Pure alcohol', 'Chain', 'Rat', 'Chalk', 'Rum', 'Chisel', 'Salve', 'Climbing hook', 'Scissors', 'Compass', 'Sealing wax', 'Copper wire', 'Sewing needle', 'Crowbar', 'Sextant', 'Dice', 'Shovel', 'Door ram', 'Silk rope', 'Ear trumpet', 'Sledgehammer', 'Ether', 'Smokebomb', 'Fire oil', 'Smoked goggles', 'Fishing hook', 'Soap', 'Flashbomb', 'Spikes', 'Flashpowder', 'Spyglass', 'Garlic', 'Stake', 'Glue', 'Steel mirror', 'Grappling hook', 'Sundial', 'Grease', 'Tent', 'Hacksaw', 'Thick gloves', 'Hammer', 'Tinderbox', 'Hand drill', 'Torch', 'Hemp rope', 'Trumpet', 'Hog holder', 'Twine', 'Hooded lantern', 'Vial', 'Hound', 'Waterskin', 'Hourglass', 'Whetstone', 'Incense', 'Whistle', 'Iron pot', 'Wolfsbane']]
    , ['items', ['Amulet', 'Lyre', 'Arrowhead', 'Manifesto', 'Birdcage', 'Map', 'Mascara', 'Bowl', 'Box', 'Military orders', 'Brooch', 'Mirror', 'Button', 'Orb', 'Card', 'Cipher', 'Paintbrush', 'Clock', 'Painting', 'Passport', 'Coin', 'Pearl', 'Comb', 'Perfume', 'Crystal', 'Pipe', 'Cup', 'Pipes', 'Degree', 'Poem', 'Doll', 'Portrait', 'Drum', 'Egg', 'Potion recipe', 'Embroidery', 'Prayer', 'Pressed flower', 'Feather', 'Purse', 'Figurine', 'Puzzle box', 'Finger bone', 'Pyramid', 'Flag', 'Razor', 'Flute', 'Ribbon', 'Ring', 'Food recipe', 'Rouge', 'Fork', 'Shopping list', 'Game piece', 'Signet ring', 'Gem', 'Sketchbook', 'Hair oil', 'Skull', 'Hairbrush', 'Snuffbox', 'Handkerchief', 'Spatula', 'Horn', 'Icon', 'Spoon', 'Jar', 'Star chart', 'Key', 'Ticket', 'Knife', 'Ladle', 'Tooth', 'Leg bone', 'Lens', 'Treaty', 'Letter', 'Tuning fork', 'List of demands', 'Wand', 'Lock of hair', 'Warrant', 'Locket', 'Lotion', 'Wine', 'Lute', 'Yarn']]
    , ['books', ['Adventure novel', 'Laws', 'Agriculture', 'Letters', 'Almanac', 'Libraries', 'Anatomy', 'Logic', 'Ancient history', 'Lost empires', 'Archaeology', 'Lost places', 'Architecture', 'Love poems', 'Astrology', 'Bestiary', 'Mathematics', 'Biography', 'Medicine', 'Blackmail', 'Modern history', 'Botany', 'Calendars', 'Music', 'Mystery Novel', 'Comedic novel', 'Mythology', 'Commerce', 'Nation', 'Condemnation', 'Navigation', 'Confession', 'Oceanography', 'Conspiracies', 'Painting', 'Cookbook', 'Planar studies', 'Criminal secrets', 'Politics', 'Cryptography', 'Culture', 'Prayers', 'Customs', 'Diplomacy', 'Propaganda', 'Prophecies', 'Divination', 'Psychology', 'Region', 'Religion', 'Epic poems', 'Rhetoric', 'Espionage', 'Romantic novel', 'Ethics', 'Etiquette', 'Sages', 'Sayings', 'Fashion', 'Sculpture', 'Finance', 'Secret societies', 'Fishing', 'Shipbuilding', 'Folklore', 'Shrines', 'Genealogy', 'Siegecraft', 'Geography', 'Songs', 'Geology', 'Ghosts', 'State secrets', 'Gods', 'Sword fighting', 'Hagiography', 'Theology', 'Heraldry', 'Horror stories', 'Treasures', 'Hunting', 'Utopian novel', 'Husbandry', 'War chronicle', 'Journal', 'Who\'s who', 'Language', 'Witch-hunting']]
    , ['clothing', ['Alb', 'Hood', 'Arm wrap', 'Hose', 'Arming doublet', 'Hounskull helm', 'Bascinet', 'Houppeland', 'Belt', 'Jacket', 'Beret', 'Jerkin', 'Bicorn hat', 'Kerchief', 'Blouse', 'Kilt', 'Bodice', 'Kirtle', 'Bonnet', 'Leg wrap', 'Boots', 'Maniple', 'Bracelet', 'Mask', 'Braies', 'Mitre', 'Breastplate', 'Nasal helm', 'Breeches', 'Necklace', 'Buckler', 'Nightcap', 'Cap', 'Pauldron', 'Cape', 'Petticoat', 'Cassock', 'Pocket', 'Chaperon', 'Pointed hat', 'Chasuble', 'Purse', 'Cincture', 'Rerebrace', 'Cloak', 'Robe', 'Clogs', 'Sabatons', 'Coat', 'Salet', 'Codpiece', 'Sandals', 'Corset', 'Sash', 'Cotte', 'Scarf', 'Cowl', 'Shield', 'Cravat', 'Shirt', 'Curiass', 'Shoes', 'Dalmatic', 'Skirt', 'Doublet', 'Sleeves', 'Dress', 'Slippers', 'Earing', 'Smock', 'Eyepatch', 'Socks', 'Fez', 'Stockings', 'Frog mouth helm', 'Stole', 'Gambeson', 'Surcoat', 'Gauntlet', 'Surplice', 'Girdle', 'Tabard', 'Gloves', 'Tower shield', 'Gorget', 'Tricorn hat', 'Gown', 'Trousers', 'Great helm', 'Tunic', 'Greaves', 'Turban', 'Hat', 'Vambrace', 'Hauberk', 'Veil', 'Headdress', 'Vest', 'Helmet', 'Wimple']]
    , ['fabrics', ['Alligator skin', 'Jute', 'Alpaca wool', 'Lace', 'Lamb wool', 'Badger skin', 'Lambskin', 'Bamboo weave', 'Leather', 'Barkcloth', 'Leopard skin', 'Bearskin', 'Linen', 'Beaver skin', 'Lion skin', 'Blanket', 'Llama wool', 'Brass', 'Mail', 'Brocade', 'Mesh', 'Bronze', 'Mink fur', 'Burlap', 'Mink skin', 'Calfskin', 'Mohair wool', 'Calico', 'Camel hair', 'Muslin', 'Camel skin', 'Oilcloth', 'Canvas', 'Ostrich skin', 'Cashmere wool', 'Otter skin', 'Cat hair', 'Patchwork', 'Chambray', 'Pig skin', 'Chiffon', 'Quilt', 'Chino', 'Rabbit skin', 'Coconut fiber', 'Rags', 'Copper', 'Rat skin', 'Corduroy', 'Reindeer skin', 'Cotton', 'Sailcloth', 'Cow skin', 'Satin', 'Crepe', 'Sealskin', 'Damask', 'Seersucker', 'Deerskin', 'Sheepskin', 'Denim', 'Sheep wool', 'Dog hair', 'Silk', 'Eel skin', 'Snake skin', 'Felt', 'Squirrel skin', 'Fish skin', 'Steel', 'Fishnet', 'Stingray skin', 'Flannel', 'Suede', 'Flax', 'Taffeta', 'Fleece', 'Tartan', 'Fox skin', 'Terrycloth', 'Gauze', 'Tiger skin', 'Gingham', 'Tinsel', 'Goatskin', 'Tulle', 'Grass weave', 'Tweed', 'Hemp', 'Twill', 'Herringbone', 'Velour', 'Horse hair', 'Velvet', 'Horse skin', 'Wolf skin', 'Iron', 'Yak wool']]
    , ['weapons', ['Arming sword', 'Longsword', 'Backsword', 'Lucerne hammer', 'Bardiche', 'Mace', 'Baton', 'Machete', 'Battleaxe', 'Man catcher', 'Beheading sword', 'Maul', 'Bill hook', 'Messer', 'Blowgun', 'Meteor hammer', 'Blowpipe', 'Military fork', 'Boar spear', 'Morningstar', 'Bolas', 'Nunchaku', 'Boomerang', 'Pickaxe', 'Brass knuckles', 'Pike', 'Bullet crossbow', 'Poleaxe', 'Butterfly sword', 'Push dagger', 'Censer flail', 'Ranseur', 'Cestus', 'Rapier', 'Chain whip', 'Recurve bow', 'Chakram', 'Rondel dagger', 'Claymore', 'Rope dart', 'Club', 'Sabre', 'Crossbow', 'Sai', 'Cutlass', 'Scimitar', 'Dagger', 'Scourge', 'Dao', 'Shortbow', 'Deer horn knives', 'Shortsword', 'Dirk', 'Shuriken', 'Double flail', 'Sickle', 'Emeici', 'Side sword', 'Falchion', 'Sling', 'Flail', 'Slingshot', 'Flambard', 'Spear', 'Flying claws', 'Staff', 'Gauntlet sword', 'Stave sling', 'Gladius', 'Stiletto', 'Glaive', 'Swordstaff', 'Halberd', 'Tanto', 'Hatchet', 'Three-part staff', 'Hook sword', 'Throwing axe', 'Horsebow', 'Throwing knife', 'Hunting knife', 'Tiger claws', 'Ice pick', 'Tonfa', 'Javelin', 'Trident', 'Katana', 'Triple flail', 'Katar', 'Wakizashi', 'Khopesh', 'War scythe', 'Kukri', 'Warhammer', 'Lance', 'Warpick', 'Lasso', 'Whip', 'Longbow', 'Zweihander']]
]);

const phases = ['morning','afternoon','night'];

let phase_count = 0;

// FUNCTION TO ROLL RANDOM MYTH PHASE
function nextPhase() {
    // SET PHASE VALUES
    phase_count+=1;
    setInner('phase',phases[(phase_count - 1) % 3])
    setInner('day_count',Math.ceil(phase_count / 3))
    // ROLL FOR MYTH ENCOUNTER
    let roll6 = Math.floor(Math.random() * 6) + 1;
    // ASSIGN MYTH TEXT
    switch (roll6) {
        case 1:
            // ENCOUNTER RANDOM MYTH
            roll6 = Math.floor(Math.random() * 6) + 1;
            setInner('myths', 'The Company encounters a random Myth: #' + roll6 + '.');
            break;
        case 2 || 3:
            // ENCOUNTER NEAREST MYTH
            setInner('myths', 'The Company encounters the nearest Myth.');
            break;
        default:
            // ENCOUNTER LANDMARK
            setInner('myths', 'The Company encounters this hex\'s Landmark.');
            break;
    }

    // ROLL AND ASSIGN NATURE FEATURES
    for (let [key, value] of hex_sparks) {
        setInner(key, value[Math.floor(Math.random() * 12)]);
        if (key == 'location') {
            setInner(key, value[Math.floor(Math.random() * 100)]);
        }
    }
}

function generatePerson() {
    // ROLL FOR KNIGHT, VAGABOND, VASSAL
    let roll6 = Math.floor(Math.random() * 6) + 1;
    // ASSIGN TEXT
    switch (roll6) {
        case 1:
            // KNIGHT
            roll6 = Math.floor(Math.random() * 6) + 1;
            let roll12 = Math.floor(Math.random() * 12) + 1;
            setInner('kvv', 'This person is a Knight who has sworn the Oath: The ' + roll6 + '-' + roll12 + ' Knight.');
            break;
        case 2 || 3:
            // VAGABOND
            setInner('kvv', 'This person is a Vagabond, their loyalty is their own.');
            break;
        default:
            // VASSAL
            setInner('kvv', 'This person is a Vassal of the Realm.');
            break;
    }

    // ROLL AND ASSIGN PERSON FEATURES
    for (let [key, value] of people_sparks) {
        setInner(key, value[Math.floor(Math.random() * 12)]);
    }
}

function generateCombat() {
    // ROLL AND ASSIGN COMBAT FEATURES
    for (let [key, value] of combat_sparks) {
        setInner(key, value[Math.floor(Math.random() * 12)]);
    }
}

function generateHolding() {
    // ROLL AND ASSIGN HOLDING FEATURES
    for (let [key, value] of holding_sparks) {
        setInner(key, value[Math.floor(Math.random() * 12)]);
    }
}

function generateLocation() {
    // ROLL AND ASSIGN LOCATION FEATURES
    for (let [key, value] of knave_locations) {
        setInner(key, value[Math.floor(Math.random() * value.length)]);
    }
}

function generateMagic() {
    // ROLL AND ASSIGN MAGIC FEATURES
    for (let [key, value] of knave_magic) {
        setInner(key, value[Math.floor(Math.random() * value.length)]);
    }
}

function generateExtra() {
    // ROLL AND ASSIGN EXTRA FEATURES
    for (let [key, value] of knave_extras) {
        setInner(key, value[Math.floor(Math.random() * value.length)]);
    }
}

function setInner(element_id, text) {
    document.getElementById(element_id).innerHTML = text;
}